### ISSUE TITLE
中国象棋有长将问题。和棋规有关。

### ISSUE THREAD

**Issue by egBean** [ianfab/Fairy-Stockfish-NNUE#1]
请问你懂Chinese吗？不知道能不能看懂我提交的问题。

**Comment by lurui22230** [comment]
> 请问你懂Chinese吗？不知道能不能看懂我提交的问题。

真的假的？

**Comment by ianfab** [comment]
我不说汉语很好但是我可以使用机器翻译. "长将问题" 什么? https://github.com/ianfab/Fairy-Stockfish/issues/55 ?

**Comment by wlwwyxzyz** [comment]
作者大大有QQ没，这里交流不方便，我想把具体局面发给你看。这是棋规问题...

**Comment by ianfab** [comment]
I do not have QQ. You can either post it here or on our discord server.

**Comment by ziyue123456789** [comment]
作者你好，我是一个象棋软件爱好者，在你发布鳕鱼变体软件后，中国象棋软件圈子里很多人都测试了这个程序的水平，总体来说，在免费象棋软件里它是很强的，然而，在多次测试中，我们发现了这个程序存在一个问题。Fairy-Stockfish-NNUE不能很好地适应中国象棋规则，比如，它会连续地无效地杀王，或者连续与对方某一个棋子陷入一个循环招法中，在中国象棋软件对弈中，这些情况有可能会因为违反中国象棋规则，导致直接判定某一方输掉棋局，所以我想向你反馈，如何让程序在循环多次之后，能够改变招法，避免因为循环导致输掉棋局，希望你在之后的新版本中能够修复它。

**Comment by ianfab** [comment]
Thanks for your feedback. The topic of chasing rules is extensively discussed in https://github.com/ianfab/Fairy-Stockfish/issues/55. If you have anything to add to that conversation, please feel free to comment there.

**Comment by xiangqishare** [comment]
> 作者大大有QQ没，这里交流不方便，我想把具体局面发给你看。这是棋规问题...

是长将吗？仙鱼应该有禁止长将，就是没有写长捉规则。如果是长将，你发个fen码
