### ISSUE TITLE
hello   鳕鱼

### ISSUE THREAD

**Issue by byezilin** [ianfab/Fairy-Stockfish-NNUE#7]
你好   请问能不能告诉我，如何把训练好的权重文件nnue内置到引擎程序当中，有没有相关的工具 和教程吗？非常谢谢

**Comment by ianfab** [comment]
Unless you have any specific requirements you can simply use the official releases https://github.com/ianfab/Fairy-Stockfish-NNUE/releases and normally don't need to compile it yourself.

**Comment by ianfab** [comment]
Other than that, the code that automatically builds these releases is also public, so you can follow these steps if you want to compile yourself: https://github.com/ianfab/Fairy-Stockfish-NNUE/blob/6ca95846284b9f3b195fc271dc3c017c2878f6d9/.github/workflows/release.yml#L41-L51

**Comment by byezilin** [comment]
十分感谢你提供的上述信息，我一直还想请教一个问题，大家都知道鳕鱼是通过cpu生成数据【training_data.bin】再通过训练工具调用GPU最后得到nnue权重文件，那么训练工具必须要使用Gpu才可以吗？如果用cpu训练可不可以得到NNUE权重文件，我并非专业人士希望能够得到答案，谢谢

**Comment by ianfab** [comment]
The training uses GPU and relies on that there has to be a GPU, you can't run it with CPU only. However, this is just during the training in order to generate the NNUE. Fairy-Stockfish itself only uses CPU.

**Comment by usaa0101** [comment]
希望出个训练的基础教程   另外15的引擎希望早日出炉

**Comment by ianfab** [comment]
A tutorial for what?

**Comment by usaa0101** [comment]
15 的引擎希望早日出炉  很多人期盼尼
