### ISSUE TITLE
xiangqi large network

### ISSUE THREAD

**Issue by shuangqiao999** [ianfab/Fairy-Stockfish-NNUE#8]
Hello xiangqi can generate large network? For example, a large NNUE file like chess does the size of the file matter?

**Comment by ianfab** [comment]
You can of course feel free to ask questions, but as I mentioned earlier please use the appropriate channels. Issues on github are for bug reports, feature requests, and other concrete development related topics, not for Q&A. Please either use our [discord](https://discord.gg/FYUGgmCFB4) or the [discussions of the NNUE training repository](https://github.com/ianfab/variant-nnue-pytorch/discussions).
